apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 1. Start with the base resources
resources:
  - ../../base
# in older versions
# bases:
#   - ../../base

# 2. Apply a patch to modify the base
patches:
  - path: deployment-patch.yaml
