apiVersion: v1
kind: Config
clusters:
  - name: "cluster01"
    cluster:
      server: "https://server-url.com/k8s/clusters/cluster01"

users:
  - name: "user01"
    user:
      token: "kubeconfig-u-token"

contexts:
  - name: "context01"
    context:
      user: "user01"
      cluster: "cluster01"

current-context: "context01"
